### PR TITLE
Support find or create line item by resourceLinkId

### PR DESCRIPTION
**Pull request by hmoffatt**
Like #81 , but for searching by the line item resourceLinkId.

### CODE REVIEW

**Comment by dmitry-viskov** [comment]
hi @hmoffatt .
I'm going to merge this PR. Please fix conflicts

**Comment by hmoffatt** [comment]
Sure, I'll fix.

**Comment by hmoffatt** [comment]
I didn't have a chance to fix this yet so thanks for taking care of it!

**Comment by hmoffatt** [comment]
Thanks for merging this.

**Pull request merged**
